Finished ConsoleFileManager
stanislavopeida/opeida pull request #1
Opened 2022-01-04 21:55 UTC by stanislavopeida

2022-01-05 10:05 UTC, JustDimus requested changes

2022-01-09 11:03 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/App.cs
> +                    name = filemanager.CurrentPath;
Пофиксил

2022-01-09 11:03 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +                Console.WriteLine();
Пофиксил

2022-01-09 11:03 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +        public string CurrentPath { get; set; } = @"E:\Учёба\.NET";
Пофиксил

2022-01-09 11:04 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +            Directory.CreateDirectory(path);
В таком случае новая папка не создаётся. Если задумка другая, то переделаю под неё

2022-01-09 11:04 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +            File.Move(path, newPath);
Пофиксил

2022-01-09 11:04 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +            }
Пофиксил

2022-01-09 11:04 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +                Console.WriteLine(fileText.Substring(0, 200));
Пофиксил

2022-01-09 11:05 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +            string stringToFind = default;
Пофиксил

2022-01-09 11:05 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/FileManager.cs
> +
Не совсем понял, что нужно переделать

2022-01-09 11:05 UTC, stanislavopeida commented on ConsoleFileManager/ConsoleFileManager/Interfaces/IFileManager.cs
> +        public string CurrentPath { get; set; }
Пофиксил

2022-01-09 12:39 UTC, Gribok4E approved these changes

2022-01-09 12:40 UTC, merged